### ISSUE TITLE
"script_score: the script could not be loaded"

### ISSUE THREAD

**Issue by cperlaAFX** [textkernel/vector-search-plugin#2]
I have installed this plugin on ES 6.4.3 and successfully indexed some test data with base64 encoded and PCA reduced vectors. However, when I attempt to  query using the function score provided in the documentation I get an error which says "script_score: the script could not be loaded" (full error message below). 

The blog post you wrote along with the plugin seemed to imply that vector-search-plugin is for storing vectors. Does this mean I need to install an additional plugin to retrieve them? If so is there a suggested plugin I should install?
{
  "error": {
    "root_cause": [
      {
        "type": "query_shard_exception",
        "reason": "script_score: the script could not be loaded",
        "index_uuid": "dyNf7U2iTeCXFk7-9RFDIg",
        "index": "idea_vectors"
      }
    ],
    "type": "search_phase_execution_exception",
    "reason": "all shards failed",
    "phase": "query",
    "grouped": true,
    "failed_shards": [
      {
        "shard": 0,
        "index": "idea_vectors",
        "node": "hwGPoHktTWCcQX7M6Ri6fg",
        "reason": {
          "type": "query_shard_exception",
          "reason": "script_score: the script could not be loaded",
          "index_uuid": "dyNf7U2iTeCXFk7-9RFDIg",
          "index": "idea_vectors",
          "caused_by": {
            "type": "illegal_argument_exception",
            "reason": "script_lang not supported [binary_vector_score]"
          }
        }
      }
    ]
  },
  "status": 400
}

**Comment by EikeDehling** [comment]
Hi,

thanks for your question.  You indeed need a second plugin for the exact vector similarity scoring.  For example this one: https://github.com/muhleder/elasticsearch-vector-scoring

The plugin we developed does a quick pre-filtering, to speed up the process. The other plugin will then do the exact similarity computation.

Best regards

**Comment by cperlaAFX** [comment]
Thank you for the clarification and the work you have done producing this plugin.

Very respectfully,
Charles

**Comment by EikeDehling** [comment]
Good luck, let me know if you have more questions
